package jp.co.axio.masterMentsetSystem.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class VMUserAuditEntity {

	private String reflecionStamp;
	private String userId;
	private String employeeId;
	private String initPassword;
	private String enrollmentKbn;
	private String startDate;
	private String endDate;
	private String employmentKbn;
	private String employmentName;
	private String mailaddr;
	private String mailaddrSecound;
	private String mailaddrNotification;
	private String tel;
	private String telEx;
	private String surnameEn;
	private String surnameJp;
	private String surnameKana;
	private String middlenameEn;
	private String middlenameJp;
	private String middlenameKana;
	private String givennameEn;
	private String givennameJp;
	private String givennameKana;
	private String surnameNickEn;
	private String surnameNickJp;
	private String surnameNickKana;
	private String middlenameNickEn;
	private String middlenameNickJp;
	private String middlenameNickKana;
	private String givennameNuckEn;
	private String givennameNuckJp;
	private String givennameNuckKana;
	private String countryCode;
	private String regionCode;
	private String companyCode;
	private String companyNameEn;
	private String companyNameJp;
	private String organizationCode;
	private String organizationNameEn;
	private String organizationNameJp;
	private String positionCode;
	private String positionNameEn;
	private String positionNameJp;
	private String gradeCode;
	private String gradeNameEn;
	private String gradeNameJp;
	private String locationCode;
	private String locationNameEn;
	private String locationNameJp;
	private String kenmuInfo;
	private String deleteFlag;
	private String invalidFlag;
	private String langCode;
	private String registerId;
	private String registTs;
	private String updaterId;
	private String updateTs;
	private String expansionAttr1;
	private String expansionAttr2;
	private String expansionAttr3;
	private String expansionAttr4;
	private String expansionAttr5;
	private String expansionAttr6;
	private String expansionAttr7;
	private String expansionAttr8;
	private String expansionAttr9;
	private String expansionAttr10;
	private String expansionAttr11;
	private String expansionAttr12;
	private String expansionAttr13;
	private String expansionAttr14;
	private String expansionAttr15;
	private String expansionAttr16;
	private String expansionAttr17;
	private String expansionAttr18;
	private String expansionAttr19;
	private String expansionAttr20;
	private String expansionAttr21;
	private String expansionAttr22;
	private String expansionAttr23;
	private String expansionAttr24;
	private String expansionAttr25;
	private String expansionAttr26;
	private String expansionAttr27;
	private String expansionAttr28;
	private String expansionAttr29;
	private String expansionAttr30;
	private String expansionAttr31;
	private String expansionAttr32;
	private String expansionAttr33;
	private String expansionAttr34;
	private String expansionAttr35;
	private String expansionAttr36;
	private String expansionAttr37;
	private String expansionAttr38;
	private String expansionAttr39;
	private String expansionAttr40;
}